### ISSUE TITLE
JavaScript - Clase 10 Proyecto Ventas

### ISSUE THREAD

**Issue by CreatemyGithub19** [CodeSystem2022/Code-People-Tercer-Semestre#107]
10.4 Creamos la Clase Orden -> Parte 1 y 2

[Teclear aquí para VER el video 3](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EYyc4wLJYFNOj2ebS1mcMosB2qZnxD8Bdhs39feLV-TMfQ?e=cW492Q)

[Teclear aquí para VER el video 4](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EfrutDu09PFBpA4YZZKENKoBo2R3fk5IQWOelCGuQ2dwaw?e=46tAFt)

**Comment by Rcalb** [comment]
hice la tarea la vez pasada, no obstante Marianela la subió hace 4 horas.
