### ISSUE TITLE
JAVA - Clase 12 Proyecto estudiantes Parte 2 - 3

### ISSUE THREAD

**Issue by Marianela00** [CodeSystem2022/Code-People-Tercer-Semestre#118]
[Teclear aquí para VER el video 4](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EXUeOM56eD5EvkNoiXkSyg0BlWujkHRyy1kn5VNARems0g?e=8jR82U)

[Teclear aquí para VER el video 5](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EfJRqel_Ol5CuhKjb6_9p5sBHNSgHdGddjutkGHZAwHYxw?e=dnscde)

12.3 Comenzamos con las pruebas del método listarEstudiantes() -> solucionamos algunos errores de conexión

[Teclear aquí para VER el video 6](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/ERC0q8TXjsRFutDy0uLWF5EBPJL4iJHk0KIl8gMdiYmv2Q?e=WLMojz)

**Comment by Dany1970** [comment]
Chequear si se subió el código
