### ISSUE TITLE
JavaScript: Clase 6 Clases Parte 1. 6.1

### ISSUE THREAD

**Issue by Marianela00** [CodeSystem2022/Code-People-Tercer-Semestre#30]
6.1 Sintaxis de Clases en JavaScript: Parte 1 y 2

[Teclear aquí para VER el video 1](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EeUoBEB5W-tGrdYRitMGm1YB_whykzOH_IAP051b8lr4GQ?e=F7yMii)

[Teclear aquí para VER el video 2](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EcOgareXFddNhGZkFFaUl1kBV3pmuxyo8nqqT0Y7sn1OhQ?e=d5pMc5)

6.2 Método Get y Set: Parte Get y Parte Set

[Teclear aquí para VER el video 3](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/ESOxwJkDOiVCvmsi8cFsVG8Bs90I1JjUd5KhmCvlGflmzg?e=tKK2IA)

[Teclear aquí para VER el video 4](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EeawmbDwfDlPvFI7bIMupRUBqgK3dTX5Gn4PnTqZLO0e8w?e=UbAGUC)

Aquí deben completar una tarea asignada en el video:

Crear el método get y set para el atributo de apellido, luego modificar el apellido a través del  set y mostrar con un console.log lo que es el get donde muestra el resultado obtenido.

**Comment by CreatemyGithub19** [comment]
ok Maru
