### ISSUE TITLE
Tarea: LABORATORIO: Python: Completar leccion 08 con Clase persona y persona DAO

### ISSUE THREAD

**Issue by Rcalb** [CodeSystem2022/Code-People-Tercer-Semestre#50]
_Cargar las siguientes tareas para completar la leccion 08:_  😁😁

**8.1 Creación de la Clase Persona**

[Teclear aquí para VER el video 1](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/ETNGf9XH0pNHgzOUJQD1uR8B09WS18lmYC5egH3LP1_r7g?e=gnf6R5)

**8.2 Prueba de la Clase Persona**

[Teclear aquí para VER el video 2](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/ESzheqEqfCRJtUe5Iv9iyhkBb4htnllFvVdyZFW82s6uKA?e=z9Rale)

**8.4 Comienzo de la creación de la Clase PersonaDAO**

[Teclear aquí para VER el video 7](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EZcnxyUOsPhLuFrHvCegwxQBk-UDqIpxD_jdLa5dwzwxyQ?e=JCD9Vv)

**Comment by CreatemyGithub19** [comment]
Gracias Nico!

**Comment by Rcalb** [comment]
La tarea esta completa, pero me equivoque al copiar los títulos de los videos, ya que esta parte fue realizada por @Marianela00 en la semana 4.
En realidad quise poner que faltaba agregar los videos 5 y 6 ,de 8.3 Creación de la Clase Conexión: Parte 1, 2 y 3 para completar la lección 08:



[Teclear aquí para VER el video 5](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EZMblJZaFGRKpPzujsSKDOgBzKISEuzTvVoVyV0cOsmbtA?e=GmnNE7)



[Teclear aquí para VER el video 6](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EclpPZ-supZKu7jimTfzNRkBV1RvHhgqlUkLOYF1GITzMQ?e=hCxFTe)
