### ISSUE TITLE
Laboratorio III. Python. Clase 9. Puntos 1,2,3.

### ISSUE THREAD

**Issue by Matu8990** [CodeSystem2022/Code-People-Tercer-Semestre#65]
9.1 En la clase PersonaDao: método seleccionar

[Teclear aquí para VER el video 1](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EVAceBgkn-dOrT9IJ1f0Yh8BMumna0WbaHl_Em2FfEX2SA?e=G65gZi)

9.2 Prueba método seleccionar

[Teclear aquí para VER el video 2](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EV-MlwDbPSFBuHLOECADQ3wBCDbUhrXmZ2h2_RiqNdighg?e=vfQHof)

9.3 Método Insertar

[Teclear aquí para VER el video 3](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EYI_Gi2OUB5Lqf8Gt8Y_5DMBl4oq4Gh8_0rsgpjQdL0YPQ?e=PfZkqG)

**Comment by CreatemyGithub19** [comment]
Listo tarea finalizada
