### ISSUE TITLE
Clase 10 LABORATORIO Python:Pool de conexiones con Python y Postgresql -> Parte 1:10.1 POOL DE CONEXIONES CON PYTHON Y POSTGRESQL

### ISSUE THREAD

**Issue by Rcalb** [CodeSystem2022/Code-People-Tercer-Semestre#82]
10.1 POOL DE CONEXIONES CON PYTHON Y POSTGRESQL: Parte 1 y 2

[Teclear aquí para VER el video 1](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EU_9qUc4mgFJkjqx10H1wEkBGJH-w_oXcEXUqXMvgPPSbQ?e=QXW47A)

[Teclear aquí para VER el video 2](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EQTmptQZDbVCj8degAORJMABvqfy9QRQXJ9cW_sENDldGg?e=OAhiPs)

**Comment by CreatemyGithub19** [comment]
Lista la tarea asignada por el Scrum Máster Nicolas Ricardo Calvo
