### ISSUE TITLE
Clase 10 PROGRAMACION 3 Proyecto Listar Personas: 10.1 UML y Introducción a la aplicación de Listar Personas

### ISSUE THREAD

**Issue by Rcalb** [CodeSystem2022/Code-People-Tercer-Semestre#85]
10.2 Creación de la clase Persona -> Parte 1, 2 y 3

[Teclear aquí para VER el video 3](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/ETT-QWLPHSZBi7Sunf73iPsBfi09aU2hciGvKWFm4vblyA?e=S8Fenp)

[Teclear aquí para VER el video 4](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/ESe4hpd5VyxKgeTQSUG91FQB5TD3PXnVMnp0Xd7gA92m8w?e=XAOms8)

[Teclear aquí para VER el video 5](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EdSc3uCzoOJDtrbsZXmjdTwBpC0AzldEOKyzfgzlV2ucBg?e=2HAUTb)

**Comment by CreatemyGithub19** [comment]
Pido colaboración ya que no puedo subir mis tareas al repositorio a traves del Desktop, tengo las tareas hechas falta subirlas
