### ISSUE TITLE
Clase 10 Laboratorio javascript

### ISSUE THREAD

**Issue by Rcalb** [CodeSystem2022/Code-People-Tercer-Semestre#94]
10.1 Introducción al sistema de ventas

10.2 Creamos la Clase Producto -> Usamos Template Literals

[Teclear aquí para VER el video 1](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EV5y8e_rlLVOo61kdz98JAsBLYoxke_BGECHmvQsud42eA?e=r1g0uK)

10.3 Prueba de la Clase Producto

[Teclear aquí para VER el video 2](https://frsrutneduar-my.sharepoint.com/:v:/g/personal/abetancud_frsr_utn_edu_ar/EYyc4wLJYFNOj2ebS1mcMosB2qZnxD8Bdhs39feLV-TMfQ?e=0aCjmb)

**Comment by CreatemyGithub19** [comment]
Realizada la tarea designada por el Scrum Máster

**Comment by CreatemyGithub19** [comment]
listo la tarea
